const execute = require('./connection');
const express = require('express');
const router = express.Router();


router.post("/rptproductos", async(req,res)=>{
    const {sucursal,fecha} = req.body;
        
    let qry ='';

    qry = `SELECT        DOCPRODUCTOS.CODPROD, DOCPRODUCTOS.DESPROD, SUM(DOCPRODUCTOS.TOTALUNIDADES) AS TOTALUNIDADES, SUM(DOCPRODUCTOS.TOTALCOSTO) AS TOTALCOSTO, SUM(DOCPRODUCTOS.TOTALPRECIO) 
    AS TOTALPRECIO, PRODUCTOS.CODMARCA, MARCAS.DESMARCA
FROM            TIPODOCUMENTOS RIGHT OUTER JOIN
    DOCUMENTOS ON TIPODOCUMENTOS.CODDOC = DOCUMENTOS.CODDOC AND TIPODOCUMENTOS.EMPNIT = DOCUMENTOS.EMPNIT LEFT OUTER JOIN
    PRODUCTOS LEFT OUTER JOIN
    MARCAS ON PRODUCTOS.CODMARCA = MARCAS.CODMARCA AND PRODUCTOS.EMPNIT = MARCAS.EMPNIT RIGHT OUTER JOIN
    DOCPRODUCTOS ON PRODUCTOS.CODPROD = DOCPRODUCTOS.CODPROD AND PRODUCTOS.EMPNIT = DOCPRODUCTOS.EMPNIT ON DOCUMENTOS.CORRELATIVO = DOCPRODUCTOS.CORRELATIVO AND 
    DOCUMENTOS.CODDOC = DOCPRODUCTOS.CODDOC AND DOCUMENTOS.EMPNIT = DOCPRODUCTOS.EMPNIT
WHERE        (DOCUMENTOS.EMPNIT = '${sucursal}') AND (DOCUMENTOS.FECHA = '${fecha}') AND (TIPODOCUMENTOS.TIPODOC = 'ENV')
GROUP BY DOCPRODUCTOS.CODPROD, DOCPRODUCTOS.DESPROD, PRODUCTOS.CODMARCA, MARCAS.DESMARCA
ORDER BY DOCPRODUCTOS.DESPROD;`     
  
    execute.Query(res,qry);

});


router.post("/rptordenes", async(req,res)=>{
    const {sucursal,fecha} = req.body;
        
    let qry ='';

    qry = `SELECT        DOCUMENTOS.EMPNIT, DOCUMENTOS.FECHA, DOCUMENTOS.CODDOC, DOCUMENTOS.CORRELATIVO, DOCUMENTOS.HORA, DOCUMENTOS.MINUTO, DOCUMENTOS.DOC_NIT AS NIT, 
    DOCUMENTOS.DOC_NOMCLIE AS NOMCLIE, DOCUMENTOS.DOC_DIRCLIE AS DIRCLIE, DOCUMENTOS.CODVEN, EMPLEADOS.NOMEMPLEADO AS MESERO, DOCPRODUCTOS.CODPROD, DOCPRODUCTOS.DESPROD, 
    DOCPRODUCTOS.TOTALUNIDADES, DOCPRODUCTOS.PRECIO, DOCPRODUCTOS.TOTALPRECIO, RESTAURANTE_MESAS.DESMESA
FROM            DOCUMENTOS LEFT OUTER JOIN
    RESTAURANTE_MESAS ON DOCUMENTOS.NOCORTE = RESTAURANTE_MESAS.ID AND DOCUMENTOS.EMPNIT = RESTAURANTE_MESAS.EMPNIT LEFT OUTER JOIN
    EMPLEADOS ON DOCUMENTOS.CODVEN = EMPLEADOS.CODEMPLEADO AND DOCUMENTOS.EMPNIT = EMPLEADOS.EMPNIT LEFT OUTER JOIN
    TIPODOCUMENTOS ON DOCUMENTOS.CODDOC = TIPODOCUMENTOS.CODDOC AND DOCUMENTOS.EMPNIT = TIPODOCUMENTOS.EMPNIT LEFT OUTER JOIN
    DOCPRODUCTOS ON DOCUMENTOS.CORRELATIVO = DOCPRODUCTOS.CORRELATIVO AND DOCUMENTOS.CODDOC = DOCPRODUCTOS.CODDOC AND DOCUMENTOS.EMPNIT = DOCPRODUCTOS.EMPNIT
WHERE        (TIPODOCUMENTOS.TIPODOC = 'ENV') AND (DOCUMENTOS.EMPNIT = '${sucursal}') AND (DOCUMENTOS.FECHA = '${fecha}')
 ORDER BY DOCUMENTOS.CODDOC, DOCUMENTOS.CORRELATIVO, DOCPRODUCTOS.DESPROD`     
  
    execute.Query(res,qry);

});




module.exports = router;
