const execute = require('./connection');
const express = require('express');
const router = express.Router();


router.post("/rptproductos", async(req,res)=>{
    const {sucursal,fecha} = req.body;
        
    let qry ='';

    qry = `SELECT        DOCPRODUCTOS.CODPROD, DOCPRODUCTOS.DESPROD, SUM(DOCPRODUCTOS.TOTALUNIDADES) AS TOTALUNIDADES, SUM(DOCPRODUCTOS.TOTALCOSTO) AS TOTALCOSTO, SUM(DOCPRODUCTOS.TOTALPRECIO) 
    AS TOTALPRECIO, PRODUCTOS.CODMARCA, MARCAS.DESMARCA
FROM            TIPODOCUMENTOS RIGHT OUTER JOIN
    DOCUMENTOS ON TIPODOCUMENTOS.CODDOC = DOCUMENTOS.CODDOC AND TIPODOCUMENTOS.EMPNIT = DOCUMENTOS.EMPNIT LEFT OUTER JOIN
    PRODUCTOS LEFT OUTER JOIN
    MARCAS ON PRODUCTOS.CODMARCA = MARCAS.CODMARCA AND PRODUCTOS.EMPNIT = MARCAS.EMPNIT RIGHT OUTER JOIN
    DOCPRODUCTOS ON PRODUCTOS.CODPROD = DOCPRODUCTOS.CODPROD AND PRODUCTOS.EMPNIT = DOCPRODUCTOS.EMPNIT ON DOCUMENTOS.CORRELATIVO = DOCPRODUCTOS.CORRELATIVO AND 
    DOCUMENTOS.CODDOC = DOCPRODUCTOS.CODDOC AND DOCUMENTOS.EMPNIT = DOCPRODUCTOS.EMPNIT
WHERE        (DOCUMENTOS.EMPNIT = '${sucursal}') AND (DOCUMENTOS.FECHA = '${fecha}') AND (TIPODOCUMENTOS.TIPODOC = 'ENV')
GROUP BY DOCPRODUCTOS.CODPROD, DOCPRODUCTOS.DESPROD, PRODUCTOS.CODMARCA, MARCAS.DESMARCA
ORDER BY DOCPRODUCTOS.DESPROD;`     
  
    execute.Query(res,qry);

});



module.exports = router;
